get https://api.themoviedb.org/3/search/movie?api_key=b5028af7e23f88044b6946e9c41743d8&query=12+angry+men

###

get https://us-central1-involvement-api.cloudfunctions.net/capstoneApi/apps/uxSepZBDcek163Ux7n5I/likes

###

get https://us-central1-involvement-api.cloudfunctions.net/capstoneApi/apps/uxSepZBDcek163Ux7n5I/comments?item_id=The%20Shawshank%20Redemption
